version: '2'
services:
    apache:
        build:
            context: ./apache
            dockerfile: Dockerfile
        ports:
         - 80:80
        volumes:
         - ./Sites:/var/www/html/
    app-be-database:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: testdb # This variable is optional and allows you to specify the name of a database to be created on image startup. If a user/password was supplied (see below) then that user will be granted superuser access (corresponding to GRANT ALL) to this database.
            MYSQL_USER: admin # These variables are optional, used in conjunction to create a new user and to set that user's password. This user will be granted superuser permissions (see above) for the database specified by the MYSQL_DATABASE variable. Both variables are required for a user to be created.
            MYSQL_PASSWORD: admin
        ports:
            - '3306:3306'
        volumes:
            - ./.volumes/app-be-database:/var/lib/mysql

